// react-dashboard/src/App/Common/Dashboard/index.js
import React, { useState, useEffect, Suspense, lazy } from "react";
import Loading from "../Loading";
import ErrorPage from "../ErrorPage";
import { withI18n } from "../../I18n";
import "./styles.scss";

const ProfileInfo = lazy(() => import(/* webpackChunkName: "ProfileInfo" */ "./ProfileInfo"));
const CV = lazy(() => import(/* webpackChunkName: "CV" */ "./CV"));
const Contact = lazy(() => import(/* webpackChunkName: "Contact" */ "./Contact"));

const Dashboard = ({ personalInfo, showContacts, i18n: { getText, lang } }) => {
  return personalInfo ? (
    personalInfo.name ? (
      <Suspense fallback={<Loading />}>
        <main className="dashboard-container">
          <section className="side-bar">
            <ProfileInfo
              name={personalInfo.name}
              nickname={personalInfo.nickname}
              username={personalInfo.username}
              age={personalInfo.age}
              birthdate={personalInfo.birthdate}
              origin={personalInfo.origin}
              showReturn={showContacts}
            />
          </section>
          <section className="cv">
            <CV
              studies={personalInfo.studies}
              work={personalInfo.work}
              hobbies={personalInfo.hobbies}
            />
          </section>
          {
            showContacts ? <section className="contacts">
              <h2>{getText('dashboard_contacts_title', lang)}</h2>
              {personalInfo.contacts.length ? personalInfo.contacts.map((contact, idx) => (
                <Contact key={idx} {...contact}></Contact>
              )) : <p>{getText('dashboard_contacts_empty', lang)}</p>}
            </section> : null
          }
          
        </main>
      </Suspense>
    ) : (
      showContacts ? <ErrorPage message={getText('dashboard_error_404', lang)} /> : <Loading />
    )
  ) : (
    <Loading />
  );
};

export default withI18n(Dashboard);

// svelte-dashboard/src/components/Common/Dashboard/Dashboard.svelte
<script>
  import { getContext } from 'svelte';
  import "./styles.scss";

  export let personalInfo, showContacts;

  const getText = getContext('getText');
  const lang = getContext('lang');
</script>

<main id="dashboard-container">
  <section id="side-bar">
    {#await import(/* webpackChunkName: "ProfileInfo" */ './ProfileInfo/ProfileInfo.svelte') then c}
      <svelte:component
        this={c.default}
        name={personalInfo.name}
        nickname={personalInfo.nickname}
        username={personalInfo.username}
        age={personalInfo.age}
        birthdate={personalInfo.birthdate}
        origin={personalInfo.origin}
        showReturn={showContacts} />
    {/await}
  </section>
  <section id="cv">
    {#await import(/* webpackChunkName: "CV" */ './CV/CV.svelte') then c}
      <svelte:component
        this={c.default}
        studies={personalInfo.studies}
        work={personalInfo.work}
        hobbies={personalInfo.hobbies} />
    {/await}
  </section>
  {#if showContacts}
    {#await import(/* webpackChunkName: "Contact" */ './Contact/Contact.svelte') then c}
      <section id="contacts">
        <h2>{getText('dashboard_contacts_title', $lang)}</h2>
        {#if personalInfo.contacts.length}
          {#each personalInfo.contacts as contact}
            <svelte:component this={c.default} {...contact} />
          {/each}
        {:else}
          <p>{getText('dashboard_contacts_empty', $lang)}</p>
        {/if}
      </section>
    {/await}
  {/if}
</main>
