// react-dashboard/src/App/EditUserPage/HobbiesInfo/index.js
import React, { useState } from "react";
import {
  addActivity,
  deleteActivity,
  addPreference,
  deletePreference
} from "../effects/actions";
import { withI18n } from "../../I18n";

const HobbiesInfo = ({ dispatch, hobbies, i18n: { getText, lang } }) => {
  const [activity, setActivity] = useState(undefined);
  const [preference, setPreference] = useState({
    category: undefined,
    title: ""
  });

  const handleAddPreference = () => {
    const { category, title } = preference;
    dispatch(addPreference(category, title));
  };

  const handleDeletePreference = (category, idx) => {
    dispatch(deletePreference(category, idx));
  };

  const handleAddActivity = () => {
    dispatch(addActivity(activity));
  };

  const handleDeleteActivity = idx => {
    dispatch(deleteActivity(idx));
  };

  return (
    <section className="form-section">
      <h3 className="form-section-title">
        {getText("edit-user-page_hobbies-info_title", lang)}
      </h3>
      <div>
        {hobbies && hobbies.activities ? (
          <ul className="form-list">
            {hobbies.activities.map((activity, idx) => (
              <li key={idx} className="form-list-item">
                <span>
                  {activity}
                  <button
                    type="button"
                    onClick={() => handleDeleteActivity(idx)}
                  >
                    {getText("generic_delete", lang)}
                  </button>
                </span>
              </li>
            ))}
          </ul>
        ) : null}
        <label for="activities">
          {getText("edit-user-page_hobbies-info_activities", lang)}
        </label>
        <input
          name="activities"
          placeholder={getText('edit-user-page_hobbies-info_activities_placeholder', lang)}
          onChange={e => setActivity(e.target.value)}
        />
        {activity ? (
          <button type="button" onClick={() => handleAddActivity()}>
            {getText("generic_add")}
          </button>
        ) : null}
      </div>
      <h3>{getText("edit-user-page_hobbies-info_preferences", lang)}</h3>
      <div>
        {hobbies && hobbies.preferences ? (
          <div className="form-list-row">
            {Object.entries(hobbies.preferences).map(
              ([category, list], idx) => (
                <ul key={idx} className="form-list">
                  {getText(`edit-user-page_hobbies-info_preferences_category_${category}`, lang)}
                  {list.map((elem, idx) => (
                    <li className="form-list-item" key={idx}>
                      <span>
                        {elem}
                        <button
                          type="button"
                          onClick={() => handleDeletePreference(category, idx)}
                        >
                          {getText("generic_delete", lang)}
                        </button>
                      </span>
                    </li>
                  ))}
                </ul>
              )
            )}
          </div>
        ) : null}
        <label for="pref-category">
          {getText("edit-user-page_hobbies-info_preferences_category", lang)}
        </label>
        <select
          name="pref-category"
          onChange={e => {
            setPreference({ ...preference, category: e.target.value });
          }}
        >
          <option selected>{getText("generic_select", lang)}</option>
          {["music", "series", "movies", "sports", "books", "anime", "snacks"].map(
            (category, idx) => (
              <option key={idx} value={category}>
                {getText(
                  `edit-user-page_hobbies-info_preferences_category_${category}`, lang
                )}
              </option>
            )
          )}
        </select>
        {preference.category ? (
          <React.Fragment>
            <label for="pref-title">{getText("edit-user-page_hobbies-info_preferences_title", lang)}</label>
            <input
              name="pref-title"
              placeholder={getText("edit-user-page_hobbies-info_preferences_title_placeholder", lang)}
              onChange={e =>
                setPreference({ ...preference, title: e.target.value })
              }
            />
            {preference.title ? (
              <button type="button" onClick={() => handleAddPreference()}>
                {getText("generic_add", lang)}
              </button>
            ) : null}
          </React.Fragment>
        ) : null}
      </div>
    </section>
  );
};

export default withI18n(HobbiesInfo);

// svelte-dashboard/src/components/EditUserPage/HobbiesInfo/HobbiesInfo.svelte
<script>
  import { 
    addPreference, 
    deletePreference, 
    addActivity, 
    deleteActivity 
  } from '../effects/actions';
  import { getContext } from 'svelte';

  export let dispatch, hobbies;

  const getText = getContext('getText');
  const lang = getContext('lang');

  let activity;
  let preference = {
    category: undefined,
    title: ""
  };

  const handleAddPreference = () => {
    const { category, title } = preference;
    dispatch(addPreference(category, title));
  };

  const handleDeletePreference = (category, idx) => {
    dispatch(deletePreference(category, idx));
  };

  const handleAddActivity = () => {
    dispatch(addActivity(activity));
  };

  const handleDeleteActivity = idx => {
    dispatch(deleteActivity(idx));
  };
</script>

<section class="form-section">
  <h3 class="form-section-title">
    {getText("edit-user-page_hobbies-info_title", $lang)}
  </h3>
  <div>
    {#if hobbies && hobbies.activities}
      <ul class="form-list">
        {#each hobbies.activities as activity, idx}
        <li class="form-list-item">
          <span>
            {activity}
            <button
              type="button"
              on:click={() => handleDeleteActivity(idx)}
            >
              {getText("generic_delete", $lang)}
            </button>
          </span>
        </li>
        {/each}
      </ul>
    {/if}
    <label for="activities">
      {getText("edit-user-page_hobbies-info_activities", $lang)}
    </label>
    <input
      name="activities"
      placeholder={getText('edit-user-page_hobbies-info_activities_placeholder', $lang)}
      bind:value={activity}
    />
    {#if activity}
      <button type="button" on:click={() => handleAddActivity()}>
        {getText("generic_add")}
      </button>
    {/if}
  </div>
  <h3>{getText("edit-user-page_hobbies-info_preferences", $lang)}</h3>
  <div>
    {#if hobbies && hobbies.preferences}
      <div class="form-list-row">
        {#each Object.entries(hobbies.preferences) as [category, list], idx}
          <ul class="form-list">
              {getText(`edit-user-page_hobbies-info_preferences_category_${category}`, $lang)}
              {#each list as elem}
                <li class="form-list-item">
                  <span>
                    {elem}
                    <button
                      type="button"
                      on:click={() => handleDeletePreference(category, idx)}
                    >
                      {getText("generic_delete", $lang)}
                    </button>
                  </span>
                </li>
              {/each}
            </ul>
        {/each}
      </div>
    {/if}
    <label for="pref-category">
      {getText("edit-user-page_hobbies-info_preferences_category", $lang)}
    </label>
    <select
      name="pref-category"
      bind:value={preference.category}
    >
      <option value={undefined}>{getText("generic_select", $lang)}</option>
      {#each ["music", "series", "movies", "sports", "books", "anime", "snacks"] as category}
        <option value={category}>
            {getText(
              `edit-user-page_hobbies-info_preferences_category_${category}`, $lang
            )}
          </option>
      {/each}
    </select>
    {#if preference.category}
      <label for="pref-title">{getText("edit-user-page_hobbies-info_preferences_title", $lang)}</label>
      <input
        name="pref-title"
        placeholder={getText("edit-user-page_hobbies-info_preferences_title_placeholder", $lang)}
        bind:value={preference.title}
      />
      {#if preference.title}
        <button type="button" on:click={() => handleAddPreference()}>
          {getText("generic_add", $lang)}
        </button>
      {/if}
    {/if}
  </div>
</section>
