// react-dashboard/src/App/Dashboard/index.js
import React, { useState, useEffect, Suspense, lazy } from "react";
import { useParams } from "react-router-dom";
import { formattedName } from "../../utils";
import Loading from "../Common/Loading";
import "./styles.scss";

const ProfileInfo = lazy(() => import("./ProfileInfo"));
const CV = lazy(() => import("./CV"));
const Contact = lazy(() => import("./Contact"));

const Dashboard = () => {
  const [personalInfo, setPersonalInfo] = useState(undefined);
  const { user } = useParams();

  useEffect(() => {
    const fetchPersonalInfo = async () => {
      const response = await fetch(
        `http://localhost:8080/personal-info/${formattedName(user)}`
      );
      const data = await response.json();

      setPersonalInfo(data);
    };
    fetchPersonalInfo();
  }, [user]);
  return personalInfo ? (
    personalInfo.name ? (
      <Suspense fallback={<Loading />}>
        <main id="dashboard-container">
          <section id="side-bar">
            <ProfileInfo
              name={personalInfo.name}
              nickname={personalInfo.nickname}
              username={personalInfo.username}
              age={personalInfo.age}
              birthdate={personalInfo.birthdate}
              origin={personalInfo.origin}
            />
          </section>
          <section id="cv">
            <CV
              studies={personalInfo.studies}
              work={personalInfo.work}
              hobbies={personalInfo.hobbies}
            />
          </section>
          <section id="contacts">
            {personalInfo.contacts.map((contact, idx) => (
              <Contact key={idx} {...contact}></Contact>
            ))}
          </section>
        </main>
      </Suspense>
    ) : (
      <ErrorPage message={"Ups! No pudimos encontrar este usuario"} />
    )
  ) : (
    <Loading />
  );
};

export default Dashboard;

// svelte-dashboard/src/components/Dashboard/Dashboard.svelte
<script>
  import { formattedName } from "../../utils";
  import ProfileInfo from "./ProfileInfo/ProfileInfo.svelte";
  import CV from "./CV/CV.svelte";
  import Contact from "./Contact/Contact.svelte";
  import Loading from "../Common/Loading.svelte";
  import ErrorPage from "../Common/ErrorPage.svelte";
  import './styles.scss';

  export let params;
  let personalInfo;

  const fetchAndUpdate = async () => {
    const response = await fetch(
      `http://localhost:8080/personal-info/${formattedName(params.user)}`
    );
    const data = await response.json();
    personalInfo = data;
  }

  $: {
    if(params.user) {
      fetchAndUpdate();
    }
  } 
</script>

{#if personalInfo}
  {#if personalInfo.name}
    <main id="dashboard-container">
      <section id="side-bar">
        <ProfileInfo
          name={personalInfo.name}
          nickname={personalInfo.nickname}
          username={personalInfo.username}
          age={personalInfo.age}
          birthdate={personalInfo.birthdate}
          origin={personalInfo.origin} />
      </section>
      <section id="cv">
        <CV
          studies={personalInfo.studies}
          work={personalInfo.work}
          hobbies={personalInfo.hobbies} />
      </section>
      <section id="contacts">
        <h3>Contactos</h3>
        {#each personalInfo.contacts as contact}
          <Contact {...contact} />
        {/each}
      </section>
    </main>
  {:else}
    <ErrorPage message={'Ups! No pudimos encontrar este usuario'}/>
  {/if}
{:else}
  <Loading />
{/if}
